export const filters = {
  type_of_area_affected: [
    { id: "asc1", title: "Commercial" },
    { id: "asc3", title: "Residential" },
    { id: "asc4", title: "Food/Food Infrastructure" },
    { id: "asc6", title: "Humanitarian" },
    { id: "asc7", title: "Roads/Highways/Transport" },
    { id: "asc8", title: "Undefined" },
    { id: "asc10", title: "Religious" },
    { id: "asc11", title: "Industrial" },
    { id: "asc12", title: "Healthcare" },
    { id: "asc14", title: "School or childcare" },
    { id: "asc15", title: "Cultural" },
    { id: "asc18", title: "Administrative" },
    { id: "asc28", title: "Military" },
  ],
  weapon_system: [
    { id: "asc2", title: "Unknown" },
    { id: "asc5", title: "Air strike" },
    { id: "asc9", title: "Cruise missile" },
    { id: "asc13", title: "Ballistic missile" },
    { id: "asc16", title: "Anti-air missile" },
    { id: "asc17", title: "Cluster munitions" },
    { id: "asc19", title: "Loitering munition" },
    { id: "asc20", title: "HE tube artillery" },
    { id: "asc21", title: "HE rocket artillery" },
    { id: "asc22", title: "Vehicle mounted weapon" },
    { id: "asc23", title: "HE artillery inc mortars" },
    { id: "asc24", title: "Incendiary munitions" },
    { id: "asc25", title: "Thermobaric munition" },
    { id: "asc26", title: "Land mines" },
    { id: "asc27", title: "Small arms" },
    { id: "asc29", title: "None" },
  ],
};
